#pragma once
// Stand-in for SdmService's own command enum. Codes and provenance: docs/sdm/PROTOCOL.md §3.
// When the real SdmService lands, delete this enum and alias sdm::Command to the real one.
#include <cstdint>
#include <string_view>

namespace sdm {

enum class Command : std::uint16_t {
    NOOP = 0x000,
    SYNC = 0x001,
    RESTART = 0x002,
    CANCEL = 0x003,
    CONFIG_STATUS = 0x004,
    RECONFIG = 0x006,
    RECONFIG_MSEL = 0x007,
    RECONFIG_DATA = 0x008,
    RECONFIG_STATUS = 0x009,
    VAB_SRC_CERT = 0x00B,
    GET_IDCODE = 0x010,
    GET_CHIPID = 0x012,
    GET_USERCODE = 0x013,
    HWMON_READVOLT = 0x018,
    HWMON_READTEMP = 0x019,
    QSPI_OPEN = 0x032,
    QSPI_CLOSE = 0x033,
    QSPI_SET_CS = 0x034,
    QSPI_READ_DEVICE_REG = 0x035,
    QSPI_WRITE_DEVICE_REG = 0x036,
    QSPI_SEND_DEVICE_OP = 0x037,
    QSPI_ERASE = 0x038,
    QSPI_WRITE = 0x039,
    QSPI_READ = 0x03A,
    QSPI_DIRECT = 0x03B,
    SEU_ERR_READ = 0x03C,
    SAFE_INJECT_SEU_ERR = 0x041,
    FPGA_CONFIG_COMP = 0x045,
    REBOOT_HPS = 0x047,
    GET_SUBPARTITION_TABLE = 0x05A,
    RSU_STATUS = 0x05B,
    RSU_UPDATE = 0x05C,
    HPS_STAGE_NOTIFY = 0x05D,
    QSPI_GET_DEVICE_INFO = 0x074,
    GET_ROM_PATCH_SHA384 = 0x1B0,
    GET_DEVICEID = 0x500,
};

constexpr std::string_view name(Command c)
{
    switch (c) {
#define SDM_CMD_NAME(x) case Command::x: return #x;
        SDM_CMD_NAME(NOOP) SDM_CMD_NAME(SYNC) SDM_CMD_NAME(RESTART) SDM_CMD_NAME(CANCEL)
        SDM_CMD_NAME(CONFIG_STATUS) SDM_CMD_NAME(RECONFIG) SDM_CMD_NAME(RECONFIG_MSEL)
        SDM_CMD_NAME(RECONFIG_DATA) SDM_CMD_NAME(RECONFIG_STATUS) SDM_CMD_NAME(VAB_SRC_CERT)
        SDM_CMD_NAME(GET_IDCODE) SDM_CMD_NAME(GET_CHIPID) SDM_CMD_NAME(GET_USERCODE)
        SDM_CMD_NAME(HWMON_READVOLT) SDM_CMD_NAME(HWMON_READTEMP)
        SDM_CMD_NAME(QSPI_OPEN) SDM_CMD_NAME(QSPI_CLOSE) SDM_CMD_NAME(QSPI_SET_CS)
        SDM_CMD_NAME(QSPI_READ_DEVICE_REG) SDM_CMD_NAME(QSPI_WRITE_DEVICE_REG)
        SDM_CMD_NAME(QSPI_SEND_DEVICE_OP) SDM_CMD_NAME(QSPI_ERASE) SDM_CMD_NAME(QSPI_WRITE)
        SDM_CMD_NAME(QSPI_READ) SDM_CMD_NAME(QSPI_DIRECT) SDM_CMD_NAME(SEU_ERR_READ)
        SDM_CMD_NAME(SAFE_INJECT_SEU_ERR) SDM_CMD_NAME(FPGA_CONFIG_COMP) SDM_CMD_NAME(REBOOT_HPS)
        SDM_CMD_NAME(GET_SUBPARTITION_TABLE) SDM_CMD_NAME(RSU_STATUS) SDM_CMD_NAME(RSU_UPDATE)
        SDM_CMD_NAME(HPS_STAGE_NOTIFY) SDM_CMD_NAME(QSPI_GET_DEVICE_INFO)
        SDM_CMD_NAME(GET_ROM_PATCH_SHA384) SDM_CMD_NAME(GET_DEVICEID)
#undef SDM_CMD_NAME
    }
    return "UNKNOWN";
}

} // namespace sdm
